# Config file for automatic testing at travis-ci.org
sudo: true  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
install: 
  - sudo ./travis_install.sh
  - sudo ./tests/installTestDb.sh
script: 
  - nose2 -v